# Generated by Django 3.0.5 on 2020-05-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blog', '0007_bloglistingpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogListingPage',
        ),
    ]
