# Generated by Django 3.0.5 on 2020-05-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_bloglistingpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'blog_index_page'},
        ),
    ]
