# Generated by Django 3.0.5 on 2020-05-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200511_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={},
        ),
    ]
