# Generated by Django 3.0.5 on 2020-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
